export LOCATION_ITEMS="\
    frankfurt Германия\
    stockholm Швеция\
    tokyo Япония\
    oregon США\
    montreal Канада\
    almaty Казахстан\
    izmir Турция\
    sydney Австралия\
    amsterdam Нидерланды\
    bangalore Индия\
    singapore Сингапур\
    london Великобритания\
    warszawa Польша\
    hongkong Гонконг\
    dublin Ирландия\
    bishkek Киргизия\
    tbilisi Грузия\
    helsinki Финляндия\
    tallin Эстония\
    mexico Мексика\
    oslo Норвегия\
    palermo Италия\
    bangkok Таиланд\
    bucharest Румыния\
    lisbon Португалия\
    pisek Чехия\
    chisinau Молдова\
    riga Латвия\
    sofia Болгария\
    madrid Испания\
    zurich Швейцария\
    athens Греция\
    marseille Франция\
    johannesburg ЮАР\
    vienna Австрия\
    seoul ЮжнаяКорея\
    budapest Венгрия\
    belgrade Сербия\
    copenhagen Дания\
    yerevan Армения\
    dubai ОАЭ\
    vilnius Литва\
    cairo Египет\
    zagreb Хорватия\
    brussels Бельгия\
    reykjavik Исландия\
    minsk Беларусь\
    skopje СевернаяМакедония\
    ljubljana Словения\
    santiago Чили\
    hanoi Вьетнам\
    baku Азербайджан\
    kathmandu Непал\
    karachi Пакистан\
    ulaanbaatar Монголия\
    bratislava Словакия\
    limassol Кипр\
    ballasalla ОстровМэн\
    jakarta Индонезия\
    manila Филиппины\
    taipei Тайвань\
    tashkent Узбекистан\
    panama Панама\
    guatemala Гватемала\
    tunis Тунис\
    sarajevo БоснияиГерцеговина\
    lagos Нигерия\
    luxembourg Люксембург\
    bogota Колумбия\
    dhaka Бангладеш\
    riyadh СаудовскаяАравия\
    manama Бахрейн\
    muscat Оман\
    lima Перу\
    quito Эквадор\
    auckland НоваяЗеландия\
    montevideo Уругвай\
    tirana Албания\
    algiers Алжир\
    nairob Кения\
    phnom-penh Камбоджа\
    buenos-aires Аргентина\
    petah-tikva Израиль\
    san-juan ПуэртоРико\
    kuala-lumpur Малайзия\
    san-jose КостаРика\
    sao-paulo Бразилия\
"
